PREFIX wd:       <http://www.wikidata.org/entity/>
PREFIX wdt:      <http://www.wikidata.org/prop/direct/>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:      <http://www.w3.org/2001/XMLSchema#>
PREFIX wikibase: <http://wikiba.se/ontology#>

# Influences among people in the age Enlightenment (1590-1750).
# Nodica draws CONSTRUCT/DESCRIBE results; try your own graph queries.
#
# The "# nodica:image" marker below tells Nodica which property fills the nodes
CONSTRUCT {
  ?a wdt:P737 ?b .
  ?a wdt:P18 ?aImage .            # nodica:image
  ?b wdt:P18 ?bImage .
  ?a rdfs:label ?aLabel .
  ?b rdfs:label ?bLabel .
  wdt:P737 rdfs:label ?propertyLabel .
}
WHERE {
  ?a wdt:P31 wd:Q5 ;
     wdt:P569 ?birth ;
     wdt:P737 ?b .
  ?b wdt:P31 wd:Q5 .
  ?a wdt:P18 ?aImage .
  ?b wdt:P18 ?bImage .
  FILTER (?birth > "1590-01-01"^^xsd:dateTime && ?birth < "1750-01-01"^^xsd:dateTime)
  ?a rdfs:label ?aLabel .
  ?b rdfs:label ?bLabel .
  ?property wikibase:directClaim wdt:P737 ;
            rdfs:label ?propertyLabel .
  FILTER (LANG(?propertyLabel) = "en")
  FILTER (LANG(?aLabel) = "en")
  FILTER (LANG(?bLabel) = "en")
}
LIMIT 50
